<a href="https://colab.research.google.com/github/BalaTechis1997/Projects-and-Assignment-1/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Generate an array of zeroes using inbuilt numpy function.

import pandas as pd
import numpy as np

print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
# Run the given code and find the dot product of both arrays.

import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)
print("Dot product of both array is")
a.dot(b)


[[9 8 8 4]
 [5 6 8 3]
 [6 8 4 2]]
[[6 8 7]
 [2 2 9]
 [3 4 7]
 [6 4 8]]
Dot product of both array is


array([[118, 136, 223],
       [ 84,  96, 169],
       [ 76,  88, 158]])

In [ ]:
#Read the csv file provided using pandas and display the first 5 entries

df=pd.read_csv("data.csv")
df.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

In [ ]:
#Describe the data with all features.
print("Features of data is column name")
df.columns

Features of data is column name


Index(['OBJECTID', 'UNIT_NAME', 'DESCRIPTION', 'ACRES', 'SHAPE.AREA',
       'SHAPE.LEN'],
      dtype='object')

In [ ]:
# Find the total count of missing values for each feature.

print("Total count of missing values for each features are")
df.isnull().sum()

Total count of missing values for each features are


OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [ ]:
# Display all the unique values from the 'DESCRIPTION’ column.

df.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [ ]:
# Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.¶

print("Mean of all the values in the DESCRIPTION are")
df.groupby(['DESCRIPTION']).mean()

Mean of all the values in the DESCRIPTION are


OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [ ]:
# Generate a random sample of 10 rows from the data.

df.sample(n=10)

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
22        44       Turtle Mountain State Recreation Area  ...   0.000345   0.086487
17        38         Fahlgren Park State Recreation Area  ...   0.000010   0.013294
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
16        37                  Elkhorn State Natural Area  ...   0.000127   0.067082
2         23             Fort Abraham Lincoln State Park  ...   0.000399   0.119868
4         25                   Grahams Island State Park  ...   0.000469   0.125546
12        35        Butte St. Paul State Recreation Area  ...   0.000025   0.022095
11        32                      Sully Creek State Park  ...   0.000030   0.024016
23        45                      Cross Ranch State Park  ...   0.000274   0.180257
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806

[10 rows x 6 columns]

In [ ]:
#Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

df['New_feature'] = np.random.rand(25)
print("New feature")
df


New feature


OBJECTID  ... New_feature
0         21  ...    0.800451
1         22  ...    0.612364
2         23  ...    0.154254
3         24  ...    0.505759
4         25  ...    0.224962
5         26  ...    0.904561
6         27  ...    0.560475
7         28  ...    0.716877
8         29  ...    0.329611
9         30  ...    0.313954
10        31  ...    0.097682
11        32  ...    0.831378
12        35  ...    0.570708
13        36  ...    0.981854
14        33  ...    0.791706
15        34  ...    0.509492
16        37  ...    0.495691
17        38  ...    0.801191
18        39  ...    0.270024
19        40  ...    0.580299
20        41  ...    0.153793
21        43  ...    0.542746
22        44  ...    0.110757
23        45  ...    0.543082
24        42  ...    0.565043

[25 rows x 7 columns]

In [ ]:
# Replace zero value of column 'OBJECTID' with mean value permanently.

a=df['OBJECTID'].mean()
print("Replace zero value of column 'OBJECTID' with mean value permanently")
df.OBJECTID.fillna(a)
df

Replace zero value of column 'OBJECTID' with mean value permanently


OBJECTID  ... New_feature
0         21  ...    0.800451
1         22  ...    0.612364
2         23  ...    0.154254
3         24  ...    0.505759
4         25  ...    0.224962
5         26  ...    0.904561
6         27  ...    0.560475
7         28  ...    0.716877
8         29  ...    0.329611
9         30  ...    0.313954
10        31  ...    0.097682
11        32  ...    0.831378
12        35  ...    0.570708
13        36  ...    0.981854
14        33  ...    0.791706
15        34  ...    0.509492
16        37  ...    0.495691
17        38  ...    0.801191
18        39  ...    0.270024
19        40  ...    0.580299
20        41  ...    0.153793
21        43  ...    0.542746
22        44  ...    0.110757
23        45  ...    0.543082
24        42  ...    0.565043

[25 rows x 7 columns]